### ISSUE TITLE
Checklist for All Code Working on 1.0

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#207]
This will function as a checklist for finishing up all the upgrades to 1.0.

Please edit this file when something has been completed, and add your name next to it when you are working on it. If a package is waiting on something else, please add a sub-bullet dependency

## Solver Packages

- [x] Value Iteration
- [x] Local Approximation Value Iteration
- [x] Monte Carlo Tree Search
- [x] QMDP
- [x] FIB
- [x] SARSOP
- [x] BasicPOMCP
- [x] ARDESPOT
- [ ] DESPOT
- [x] MCVI
- [x] POMDPSolve
- [x] POMCPOW
- [x] AEMS
- [x] IncrementalPruning
- [x] Tabular TD Learning

## Other Packages
- [x] ParticleFilters
- [x] POMDPModels
    - [x] Waiting on new ModelTools release
- [x] POMDPModelTools
- [x] BeliefUpdaters
- [x] POMDPPolicies
- [x] POMDPSimulators
    - [x] Waiting on a new POMDPModels release because tests fail
- [x] POMDPTesting

**Comment by zsunberg** [comment]
Once POMDPModels 0.3.1 is merged, all tests that use GridWorld should use LegacyGridWorld in case we replace it.

**Comment by bisraelsen** [comment]
@zsunberg, I can't figure out how to edit the checklist above....can you point the way? ;-)

**Comment by zsunberg** [comment]
Hi @bisraelsen , can you click the three dots in the top right and click edit? Maybe only I can do that... regardless, if you want to work on something you can just comment here instead of editing that message.

**Comment by bisraelsen** [comment]
@zsunberg , nope edit isn't there. I'll take the MCTS solver.

**Comment by zsunberg** [comment]
Ok thanks! make sure to work off the existing PR https://github.com/JuliaPOMDP/MCTS.jl/pull/51 I'm not sure what's causing that one to fail - it might be convoluted. Let us know if you can get it to work, and no worries if there is a road block that you can't get around

**Comment by zsunberg** [comment]
@bisraelsen , were you able to make any progress on MCTS? I am planning on working on some of the tree based solvers that use MCTS in a little while

**Comment by bisraelsen** [comment]
@zsunberg , no :-) go for it
