### ISSUE TITLE
Checklist for Documentation

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#208]
This will serve as a checklist for all of the major documentation

Please edit this comment and put your name next to something if you are working on it.

## Packages that need Documenter.jl docs

- [ ] POMDPModelTools
- [ ] BeliefUpdaters
- [ ] POMDPPolicies
- [ ] POMDPSimulators
- [ ] POMDPTesting

## Examples

- [ ] Create Examples REPO
- [ ] Defining an explicit POMDP
- [ ] Defining an explicit MDP
- [ ] Defining a generative POMDP
- [ ] Running Simulations
- [ ] Using an Offline Solver
- [ ] Using an Online Solver

## Other Tasks

- [ ] Upgrade POMDPs.jl README

**Comment by zsunberg** [comment]
The Repo is here: https://github.com/JuliaPOMDP/POMDPExamples.jl

I am currently working on the generative POMDP one

**Comment by zsunberg** [comment]
Feel free to claim an example. Remember to keep everything as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) as possible by linking to other resources.

**Comment by zsunberg** [comment]
It may be good to draw from the tutorials already on POMDPs.jl, but they should be broken up (defining the problem should be broken up from solving it)

**Comment by zsunberg** [comment]
@kunalmenda, Jeremy Morton (needs a github account), the "create a guide/matrix of solver capabilities" task is the one you requested
