### ISSUE TITLE
Release v0.8 before AA228 starts on 9/23?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#255]
Hi Everyone,

I wanted to gauge thoughts on releasing POMDPs v0.8 before AA228 starts on 9/23. I think we should do it.

You can find a list of all associated issues here: https://github.com/JuliaPOMDP/POMDPs.jl/milestone/3. The biggest ones are:
- #240 (`gen` to replace `generate_x`), and
- #153 (adding a belief type parameter to `Updater`)

I think most of the work will be up to me, since #240 is my idea, but I wanted to see if anyone (especially @MaximeBouton @rejuvyesh @Shushman @lassepe @mykelk ) have any thoughts. Also, please weigh in on any of the issues marked with the `decision` tag if you have thoughts.

If you'd like to help, reply with the items that you'd be willing to help with:
- [x] I want to review the PR for #240 (this will involve some deep thinking)
- [x] I can help with major changes (like #216 or #153)
- [x] I can help review changes
- [x] I can help with updating other packages to work with 0.8 (should be mostly find-and-replace)
- [x] I can help to update the tutorials (should be mostly find-and-replace)

Finally, there is a procedure question: Should we
1. Release a version 7.3 that allows us to upgrade packages to work with 0.8 before releasing it, or
2. Just release 0.8 and then have a mad dash to update everything

I'm leaning towards (1).

I think version 0.8 will be good enough that we could consider a 1.0 release with minimal or no changes in the winter!!

**Comment by mykelk** [comment]
Sounds good to me! Let's do it!

**Comment by lassepe** [comment]
Regarding the procedure question: I would prefer first releasing 0.7.3. Having deprecation warnings in some "official" packages would be annoying and if we don't make it before 9/23, maybe also not a nice experience for students.

- [x] I can help review changes (I would like to avoid being the only reviewer on some big PR, though)
- [x] I can help update tutorials

**Comment by Shushman** [comment]
I am somewhat occupied before a 9/15 deadline, so for now, I can only commit to

- [ ] I want to review the PR for #240 (this will involve some deep thinking)

Between 9/16 - 9/23, I can assist with the below if needed

- [ ] I can help review changes
- [ ] I can help with updating other packages to work with 0.8

**Comment by Shushman** [comment]
I can't claim to have completely understood the `DBNStruct` yet, but based on my reading of it, my understanding of the problem with the previous setup, and my general understanding of all (PO)MDPs being DBNs of some form, I am in favor of the decision and will review the PR closely

**Comment by zsunberg** [comment]
It looks like since I had some trouble with #240 and we decided to try #256, we should push things back a couple days. I have adjusted the schedule above.

**Comment by zsunberg** [comment]
Didn't quite get 0.8 done by 9/9, but it should be done in the next couple of days, and I think package upgrades will be relatively easy, so I think we can still get it done by the start of the class.

**Comment by zsunberg** [comment]
Ok, looks like everything is ready. Here's a rough plan (dates are, of course, flexible):

- 9/13 Submit PR from version-0.8 to master so that people can comment
- 9/13 Register version 0.7.3 from the version-0.7 branch
- 9/19 update solver packages (may need a 0.7.4 release at some point in this process)
- 9/20 merge version-0.8 PR into master
- 9/20 release 0.8.0
- 9/23 update model packages

**Comment by zsunberg** [comment]
Ok, I made the v0.8 tag!!
