### ISSUE TITLE
Checklist for upgrading packages to work with v0.8

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#259]
For each solver/simulator/utility package, we need to perform the following:

- compat should be
  ```
  [compat]
  POMDPs = "0.7.3, 0.8"
  julia = "1"
  ```
- remove all use of `generate_` and replace calls with `gen(::DDNOut(...), ...)` and definitions with `gen(m, s, a, rng)` or `gen(::DDNNode{...}, ...)`
- remove use of n_states, n_actions, n_observations and replace with length
- If `sampletype` is implemented, change it to `Random.gentype` (but this will not be listed in the documentation)
- Consider whether any beliefs can support `history` or `currentobs` and implement them.
- for solvers: use `actions(m, b)` where possible (#226)
- Test with 0.7.3 and 0.8.0
- Register a new version

List of packages to update:

- [x] POMDPSimulators [Zach] (additional changes awaiting tag)
- [x] BeliefUpdaters [Zach] (awaiting tag)
- [x] ParticleFilters [Lasse]
- [x] POMDPModelTools [Maxime, Zach]
- [x] POMDPPolicies [Zach]
- [x] POMDPTesting [Lasse]
- [x] RLInterface [Maxime]
- [x] Value Iteration [Maxime]
- [x] Local Approximation Value Iteration [Zach]
- [x] Global Approximation Value Iteration [@Shushman]
- [x] QMDP [Jayesh]
- [x] FIB [Zach]
- [x] SARSOP [Zach]
- [x] MCTS [Lasse]
- [x] BasicPOMCP [Lasse]
- [x] ARDESPOT [Lasse]
- [x] MCVI [Zach]
- [x] POMDPSolve [Zach]
- [x] IncrementalPruning [Maxime]
- [x] POMCPOW [Lasse]
- [x] AEMS [Maxime]
- [x] TabularTDLearning [Maxime]
- [x] DeepQLearning [Maxime]

These packages should wait until *after* v0.8 is released:
- [x] BasicPOMCP (defines toy problem that needs update with v0.8)
- [x] POMDPExamples [Zach - ready to be merged]
- [x] POMDPModels [Looks like @Shushman got this]
- [ ] POMDPGallery and repos from there

**Comment by MaximeBouton** [comment]
Since v0.7.3 has been released, is this a good time to start updating? 
Should we try to set up this: https://github.com/JuliaRegistries/Registrator.jl/blob/master/README.web.md#setup-for-registry-maintainers now to make the registration easier?

**Comment by zsunberg** [comment]
Yes! Now is the time! And yes, it would be good to set registrator up. Not sure if there is a machine at SISL that would be good to use as a server, or maybe we can just run it on our local machines

**Comment by zsunberg** [comment]
@lassepe and I are going to have a little hackathon tonight, so make sure you put your name next to something if you are working on it so that we don't duplicate too much effort.

**Comment by MaximeBouton** [comment]
sounds good, I will check with @rejuvyesh to set up a sisl machine for it.

**Comment by MaximeBouton** [comment]
How does it work for the requirements without `n_states` ? 
do we want to add: 
```julia 
S = states(pomdp)
@req length(::S)
```
?

**Comment by zsunberg** [comment]
```julia
ss = states(pomdp)
@req length(::typeof(ss))
```

**Comment by MaximeBouton** [comment]
There is a chicken egg problem with JuliaPOMDP/DiscreteValueIteration .jl#34 and JuliaPOMDP/POMDPModelTools.jl#26

**Comment by zsunberg** [comment]
@MaximeBouton @rejuvyesh , did you guys happen to set up registrator?

**Comment by rejuvyesh** [comment]
We did, but it doesn't seem to work yet and it's not easy to debug :confounded:

**Comment by zsunberg** [comment]
Thanks a bunch for trying!! If the @JuliaPOMDPRegistrator handle doesn't work, does the web interface work? That would certainly be a fine way to do it.

**Comment by MaximeBouton** [comment]
not yet: https://woodstock.stanford.edu/juliapomdpregistratorweb/
I think there is something missing in the configuration of the github app.

**Comment by lassepe** [comment]
@zsunberg is there a better way to do [this](https://github.com/JuliaPOMDP/BasicPOMCP.jl/commit/f9c0b7b1596bb2c60fa924d5d55fa0fb93cf2dc3)? This seems like it's very expensive given that `insert_obs_node!` is called a lot.

**Comment by zsunberg** [comment]
Yeah... either
1) store n_actions in the tree structure
2) use the same length as other observation nodes in the tree
3) just get rid of the sizehint

**Comment by lassepe** [comment]
Okay. I guess I'll get rid of it then. In particular, because they action space size might not be constant with #226. 

By the way: did we forget to add the refactoring required to fix #226 to the checklist? Should we already modify the solvers to use `actions(m, b)`?

**Comment by zsunberg** [comment]
> they action space size might not be constant with #226.

The sizehint would still work fine - it is only a hint, but yeah, I think getting rid of it would probably be ok.

> did we forget to add the refactoring required to fix #226 to the checklist?

yes! Good thinking! can you add it?

**Comment by zsunberg** [comment]
@lassepe can you request a review from me after you do the #226 refactor for POMCPOW - I just want to make sure our design makes sense for that.

**Comment by zsunberg** [comment]
@MaximeBouton , I noticed that you had
```julia
[compat]
POMDPs = "0.7.3, 0.9.0"
```
in DiscreteValueIteration. This is not quite right - it should be "0.7.3, 0.8" as in the checklist above. See the Pkg docs for an explanation. Also make sure to test with POMDPs 0.8 by using, e.g.
```
(DiscreteValueIteration) pkg> add POMDPs#version-0.8

(DiscreteValueIteration) pkg> test
```
I will fix it in `DiscreteValueIteration`.

**Comment by MaximeBouton** [comment]
Thanks, yes the instruction above has been edited, I will make sure to get it right for the other repo

**Comment by zsunberg** [comment]
Hey guys, thanks so much for your hard work on this! Especially @MaximeBouton and @lassepe . Today I am going to make the changes to POMDPExamples just to make sure there are no big surprises and then probably release POMDPs.jl version 0.8 tonight.

@rejuvyesh were there any changes needed for QMDP? I will take a look at it later this afternoon.

**Comment by rejuvyesh** [comment]
Just had to wait on DiscreteValueIteration, should be fine otherwise. Sorry been working on ICLR deadline.

**Comment by zsunberg** [comment]
Ok, POMDPs v0.8 is released!! :tada: https://github.com/JuliaPOMDP/POMDPs.jl/releases/tag/v0.8.0

The only thing left to do is update POMDPModels. I will not be able to do this for a couple of days, so if anyone wants to jump on that, please do!

**Comment by mykelk** [comment]
Yay! Thank you for all of your contributions!

**Comment by zsunberg** [comment]
I think we are done with this now
