### ISSUE TITLE
JMLR Paper Roadmap

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#30]
I thought it might be worthwhile to have a list of deliverables that can also serve as a roadmap for the POMDPs.jl paper. 

The following is a minimal list of solvers I think we need to support. A finished solver should have extensive documentation, run tests and should be validated. 

Have to have solvers:
- [X] [ValueIteration](https://github.com/sisl/DiscreteValueIteration.jl) 
- [X] [MCTS](https://github.com/sisl/MCTS.jl) 
- [X] [QMDP](https://github.com/sisl/QMDP.jl) 
- [ ] FIB (no repo yet)
- [X] [SARSOP](https://github.com/sisl/SARSOP.jl) (needs docs)
- [X] [POMCP](https://github.com/sisl/POMCP.jl) 
- [x] [DESPOT](https://github.com/sisl/DESPOT.jl) 

Nice to have solvers (variants can now be found in [POMDPSolve](https://github.com/JuliaPOMDP/POMDPSolve.jl)):
- [ ] PBVI and simple variants (no repo)
- [ ] Witness  (no repo)
- [ ] AMDP (no repo)
- [ ] Perseus (no repo)

The following support tools are provided:
- [X] [POMDPToolbox](https://github.com/sisl/POMDPToolbox.jl) (still not clear what this should contain)
- [X] [POMDPXFile](https://github.com/sisl/POMDPXFile.jl) (SARSOP file generation and .policy file parsing)
- [X] POMDPFile 
- [ ] POMDPDistributions (Most agree we don't need this)
- [ ] POMDPSimulator (part of POMDPToolbox now)
- [ ] [PLite.jl] (https://github.com/haoyio/PLite.jl) high-level modeling language modeled after JuMP  

Miscellaneous:
- [X] Main Doc 
- [X] [POMDPModels.jl] 

Benchmarks against the following solvers would be a nice addition to the paper:
- [ ] [AIToolbox](https://github.com/Svalorzen/AI-Toolbox) (C++, supports VI, MCTS, QMDP, POMCP, Witness, AMDP, Perseus, and others)
- [x] [pomdp-solve](http://www.pomdp.org/code/) (C++, supports PBVI, Witness and others)
- [ ] [MDP Toolbox](http://www7.inra.fr/mia/T/MDPtoolbox/) (MATLAB, supports VI, policy iteration and LP methods)
- [ ] [PyMDP Toolbox](https://github.com/sawcordwell/pymdptoolbox) (python, supports VI and variants) 

Please add or edit as you see necessary.

**Comment by ebalaban** [comment]
Nice outline. I'd think that a LaTeX repository on GitHub is the way to go for the main document.

**Comment by etotheipluspi** [comment]
Closing this, since the paper is out.
